version: '2'

services:

  flash_one:
    build: .
    environment:
      - "IOTA_SEED=USERONEUSERONEUSERONEUSERONEUSERONEUSERONEUSERONEUSERONEUSERONEUSERONEUSERONEUSER"
      - "AUTH_USERNAME=user_one"
      - "AUTH_PASSWORD=password_one"
    ports:
      - "3000:3000"

  flash_two:
    build: .
    environment:
      - "IOTA_SEED=USERTWOUSERTWOUSERTWOUSERTWOUSERTWOUSERTWOUSERTWOUSERTWOUSERTWOUSERTWOUSERTWOUSER"
      - "AUTH_USERNAME=user_two"
      - "AUTH_PASSWORD=password_two"
    ports:
      - "3001:3000"

  client:
    build: example
    depends_on:
      - flash_one
      - flash_two