version: '2'

services:

  flash:
    build: .
    environment:
      - "IOTA_SEED=USERONEUSERONEUSERONEUSERONEUSERONEUSERONEUSERONEUSERONEUSERONEUSERONEUSERONEUSER"
      - "AUTH_USERNAME=user_one"
      - "AUTH_PASSWORD=password_one"
      - "MONGODB_URL=mongo_one"
    ports:
      - "3000:3000"
    depends_on:
      - mongo_one

  mongo_one:
    image: mongo
    ports:
      - "27017:27017"